name: MyAction
description: "action that creates file"

inputs:
  folder_path:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Create file
      id: create_file
      shell: bash
      run: |
        echo hello
        echo ${{ inputs.folder_path }}
        mkdir -p ${{ inputs.folder_path }}
        cd ${{ inputs.folder_path }}
        find . -type f | tee file_list.txt
        cat file_list.txt
        echo "${{ inputs.folder_path }}/file_list.txt"
        echo "::set-output name=file_path::${{ inputs.folder_path }}/file_list.txt"
    - name: Output file path
      shell: bash
      run: |
        echo "File path: ${{ inputs.folder_path }}/file_list.txt"

outputs:
  file_path:
    description: "file, created by our action"
    value: ${{ inputs.folder_path }}/file_list.txt

