name: MyAction
description: "action that creates file"

#inputs:
#  folder_path:
#    type: string
#    required: true

runs:
  using: "composite"
  steps:
    - name: Create file
      id: create_file
      shell: bash
      run: |
        echo hello
        mkdir -p new_folder
        cd new_folder
        find . -type f | tee file_list.txt
        cat file_list.txt
    - name: Output file path
      shell: bash
      run: |
        echo "File path: new_folder/file_list.txt"

#  echo folder path
#  echo ${{ inputs.folder_path }}
#  mkdir -p "${{ inputs.folder_path }}"
#  echo "This is a file created by My Action." > "${{ inputs.folder_path }}/file.txt"
#  echo "folder_path=${{ inputs.folder_path }}"

#jobs:
#  build:
#    runs-on: ubuntu-latest
#